### PR TITLE
Final edits to the imputation branch

### PR DESCRIPTION
**Pull request by storresrod**
Fixing race_eth, adding correlation table, reducing imputation iteration to 5, and adding whisker plots. Outstanding: adding bounds to imputation.

### CODE REVIEW

**Review by dc0sic — APPROVED** [review]
It looks great. Thank you!

**Comment by dc0sic** [comment]
@storresrod the whisker plots are correct. The original set and the imputed values have the same minimum and maximum for both income and net worth. The reason that these extreme values are not shown in the scatter plot of the original data is that they are paired with a missing value. The observation with the smallest pwealth is missing pincome and is not plotted. Similarly, the smallest pincome is paired with a missing pwealth.

**Comment by storresrod** [comment]
Hi Damir - I'm not seeing the problematic outliers that had been previously flagged, like -1,000,000, in the imputed wealth values in the raw data or in the distribution plots (which only show density for wealth). In my current run, the actual min and max for `pnetworth` is -935,251 and 600,000, and those also appear to be the min and maxes of the five generated imputation examples.

**Comment by dc0sic** [comment]
Correct, but what confused me is that these values are not visible in the scatter plot for the original data but are visible in the scatter plots for the imputed data sets. So yes, this is not a problem.

**Pull request merged**
